/**
* @author Abhishek Raj(abhraj786@gmail.com)
* @date 
* @description : Landing Page Wrapper.
Modification Log:
------------------------------------------------------------------------------------
Developer Mod Number Date Description
------------------------------------------------------------------------------------
*/
public class LandingPageResponseWrapper { 
    
    public DataTableResponse lstDataTableRecs; 
   
}